- name: update packages
  package:
    name: "*"
    state: latest
    update_cache: yes
    autoclean: yes

- name: install commons packages
  package:
    update_cache: yes
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - nfs-kernel-server
      - rsyslog
      - curl
      - wget
      - htop
      - python3-minimal
      - net-tools
      - build-essential
      - ca-certificates
      - vim
      - libvirt-clients
      - sudo
      - apt-transport-https
      - gpg

- name: create nfs directory
  file:
    path: "{{ nfs_path }}"
    state: directory
    mode: 0777
    owner: nobody
    group: nogroup

- name: apply template exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: "{{become_user}}"
    group: "{{become_user}}"
    mode: 0770
    backup: yes

- name: update exports
  shell: exportfs -a

- name: start nfs-server
  systemd:
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - rsyslog
    - nfs-kernel-server
