- hosts: controlplane
  become_user: "{{ become_user }}"
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - { role: commons }
    - { role: controlplane }
- hosts: nodes
  become_user: "{{ become_user }}"
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - { role: commons }
    - { role: nodes }
- hosts: nfs_servers
  become_user: "{{ become_user }}"
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - { role: nfs_server }
