# - hosts: nfs_servers
#   become_user: root
#   remote_user: debian
#   become: yes
#   roles:
#     - { role: nfs-server }

- hosts: controlplane
  become_user: root
  remote_user: debian
  become: yes
  roles:
    - { role: commons }
    - { role: controlplane }
# - hosts: nodes
#   become_user: root
#   remote_user: debian
#   become: yes
#   roles:
#     - { role: commons }
#     - { role: nodes }
