- name: add repo argo-helm
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: helm deploy argo tools
  kubernetes.core.helm:
    name: "{{ item }}"
    chart_ref: "argo/{{ item }}"
    release_namespace: "{{ item }}"
    create_namespace: true
    update_repo_cache: true
    force: true
    wait: true
    values:
      configs:
        params:
          "server.insecure": true
        cm:
          "users.anonymous.enabled": false
          "users.session.duration": "48h"
          "accounts.kvmuser": apiKey
          "accounts.kvmuser.enabled": true
          "admin.enabled": true
          url: http://argocd.local
        rbac:
          policy.csv: |
            p, kvmuser, applicationsets, create, */*, allow
            p, kvmuser, applicationsets, get, */*, allow
            p, kvmuser, applicationsets, update, */*, allow
          scopes: "[email, group]"
  with_items:
    - argocd
