- name: download helm
  unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    group: root
    mode: "0770"

- name: copy helm bin
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    group: root
    mode: "0770"
