- name: install helm
  block:
    - name: download helm
      unarchive:
        src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: root
        mode: "0770"
    - name: copy helm bin
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: root
        mode: "0770"

- name: add repo helm chart nfs-subdir-external-provisioner
  kubernetes.core.helm_repository:
    name: "nfs-subdir-external-provisioner"
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: add repo helm chart prometheus-community
  kubernetes.core.helm_repository:
    name: "prometheus-community"
    repo_url: " https://prometheus-community.github.io/helm-charts"

- name: deploy nfs-subdir-external-provisioner
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    chart_version: "4.0.18"
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: storage
    create_namespace: true
    wait: false
    values:
      storageClass:
        name: nfs
        defaultClass: true
      nfs:
        server: "{{ hostvars[groups['nfs_servers'][0]].inventory_hostname }}"
        path: "{{ nfs_path }}"
      archiveOnDelete: true

- name: deploy nfs-subdir-external-provisioner
  kubernetes.core.helm:
    name: prometheus-node-exporter
    chart_version: "4.39.0"
    chart_ref: prometheus-community/prometheus-node-exporter
    release_namespace: monitoring
    create_namespace: true
    wait: false
