- name: kubeadm init
  shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16 --v=10 > kubeadminit.log
  args:
    chdir: $HOME
    creates: kubeadminit.log

- name: wait for kubernetes api start
  wait_for:
    port: 6443
    delay: 3
    connect_timeout: 120

- name: create .kube directory
  file:
    path: /home/{{ ansible_ssh_user }}/.kube
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: root
    mode: 0770

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    owner: root
    group: root
    mode: 0770

- name: copy default cluster configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0660

- name: copy default cluster configuration to user path
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_ssh_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    group: root
    mode: 0660
