all:
  vars:
    kube_api_dns: k8sapi.jdc.net.local
    remote_user: cpd
    become_user: root
    kubeadm_version: "1.28"
    containerd_version: "1.7.23"
    runc_version: "1.1.15"
    cni_plugins_version: "1.6.0"
    k9s_version: "0.32.5"
    helm_version: "3.16.0"
    nerdctl_version: "0.22.2"
    nfs_path: /k8s
    nfs_client_cidr: 192.168.1.0/24
    metallb_loadbalancer_ip_range: 192.168.1.13-192.168.1.30
    prometheus_arch: amd64
  children:
    controlplane:
      hosts:
        192.168.1.20:
    nodes:
      hosts:
        # 192.168.1.21:
        # 192.168.1.22:
        # 192.168.1.23:
        # 192.168.1.31:
        # 192.168.1.32:
        192.168.1.33:
