all:
  vars:
    kubeadm_version: 1.28
    containerd_version: 1.7.5
    runc_version: 1.1.9
    cni_plugins_version: 1.3.0
    k9s_version: 0.27.4
    helm_version: 3.13.1
    nfs_path: /k8s
    nfs_client_cidr: 192.168.124.0/24
    metallb_loadbalancer_ip_range: 192.168.124.100-192.168.124.110
  children:
    controlplane:
      hosts:
        192.168.124.10:
    nodes:
      hosts:
        192.168.124.11:
        192.168.124.12:
    nfs_servers:
      hosts:
        192.168.124.13:
