all:
  vars:
    kubeadm_version: 1.28
    containerd_version: 1.7.5
    runc_version: 1.1.9
    cni_plugins_version: 1.3.0
    k9s_version: 0.27.4
    helm_version: 3.13.1
  children:
    controlplane:
      hosts:
        192.168.124.2:
    nodes:
      hosts:
        192.168.124.3:
        192.168.124.4:
        192.168.124.5:
    nfs_server:
      hosts:
        192.168.124.6:
