all:
  vars:
    remote_user: debian
    become_user: root
    kubeadm_version: 1.31
    containerd_version: 1.7.23
    runc_version: 1.1.15
    cni_plugins_version: 1.6.0
    k9s_version: 0.32.5
    helm_version: 3.16.0
    nerdctl_version: 0.22.2
    nfs_path: /k8s
    nfs_client_cidr: 192.168.124.0/24
    metallb_loadbalancer_ip_range: 192.168.124.100-192.168.124.110
    prometheus_version: 2.53.1
    prometheus_arch: amd64
    alertmanager_version: 0.27.0
  children:
    controlplane:
      hosts:
        192.168.124.239:
    nodes:
      hosts:
        192.168.124.67:
        192.168.124.205:
    nfs_servers:
      hosts:
        192.168.124.139:
    monitoring_servers:
      hosts:
        192.168.124.6:
