all:
  vars:
    kubeadm_version: 1.28
    containerd_version: 1.7.5
    runc_version: 1.1.9
    cni_plugins_version: 1.3.0
    k9s_version: 0.27.4
    helm_version: 3.13.1
    nfs_server_ip: 192.168.123.110
  children:
    controlplane:
      hosts:
        192.168.123.42:
    nodes:
      hosts:
        192.168.123.131:
        192.168.123.203:
        192.168.123.104:
