all:
  vars:
    remote_user: debian
    become_user: root
    kubeadm_version: 1.31
    containerd_version: 1.7.20
    runc_version: 1.1.13
    cni_plugins_version: 1.5.1
    k9s_version: 0.32.5
    helm_version: 3.15.3
    nfs_path: /k8s
    nfs_client_cidr: 192.168.124.0/24
    metallb_loadbalancer_ip_range: 192.168.124.100-192.168.124.110
  children:
    controlplane:
      hosts:
        192.168.124.191:
    nodes:
      hosts:
        192.168.124.250:
        192.168.124.86:
    nfs_servers:
      hosts:
        192.168.124.210:
