all:
  vars:
    kube_api_dns: otaconpf.ddns.net
    remote_user: debian
    become_user: root
    kubeadm_version: "1.33"
    containerd_version: "2.2.0"
    runc_version: "1.3.3"
    cni_plugins_version: "1.8.0"
    k9s_version: "0.50.16"
    helm_version: "3.19.0"
    nerdctl_version: "2.2.0"
    nfs_path: /k8s
    nfs_client_cidr: 192.168.50.0/24
    metallb_loadbalancer_ip_range: 192.168.50.50-192.168.50.51
  children:
    controlplane:
      hosts:
        192.168.50.20:
    nodes:
      hosts:
        192.168.50.21:
    nfs_servers:
      hosts:
        192.168.50.22:
