- name: create cni directory
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0766
    owner: root
    group: root

- name: download cni plugins
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz
    dest: /opt/cni/bin/
    remote_src: yes
