- name: check if kubernetes-apt-keyring.gpg exists
  stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: kubernetes_gpg_key

- name: remove keyrings directory
  file:
    state: directory
    path: /etc/apt/keyrings/
  when: kubernetes_gpg_key.stat.exists == False

- name: add kubernetes_gpg_key
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: kubernetes_gpg_key.stat.exists == False

- name: add kubernetes-apt-keyring
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_version }}/deb/ /"
    state: present
  when: kubernetes_gpg_key.stat.exists == False

- name: install kubernetes bootstrap pkgs
  package:
    update_cache: yes
    state: present
    name: "{{ item }}"
  with_items:
    - kubelet={{ kubeadm_version }}*
    - kubeadm={{ kubeadm_version }}*
    - kubectl={{ kubeadm_version }}*

- name: apt mark hold kubernetes version
  shell: apt-mark hold kubelet kubeadm kubectl >> kubernetes-hold.log
  args:
    chdir: $HOME
    creates: kubernetes-hold.log
