- name: create alertmanager system group and user
  block:
    - name: create group alertmanager
      group:
        name: alertmanager
        system: yes
    - name: create group alertmanager
      user:
        name: alertmanager
        system: yes
        group: alertmanager

- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: root
  with_items:
    - /etc/alertmanager

- name: download and extract alertmanager
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-arm64.tar.gz
    dest: /opt
    owner: alertmanager
    group: root
    remote_src: yes

- name: install alertmanager binaries
  file:
    state: link
    force: true
    src: "/opt/alertmanager-{{ alertmanager_version }}.linux-arm64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: alertmanager
    group: root
    mode: a+x
  with_items:
    - alertmanager
    - amtool

- name: create alertmanager.yml
  vars:
    DISCORD_CLUSTER_WEBHOOK_URL: "xxx"
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    mode: 0770
    owner: alertmanager
    group: root

- name: create alertmanager.service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: 0770
    owner: alertmanager
    group: root

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted
    enabled: yes
    daemon_reload: true
