- name: set new hostname
  hostname:
    name: "{{ ansible_ssh_host | replace('.','') }}"
    use: systemd

- name: SO update
  yum:
    name: "*"
    state: latest

- name: install commons
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
