- name: set new hostname
  hostname:
    name: "{{ ansible_ssh_host | replace('.','') }}"
    use: systemd

- name: SO update
  package:
    name: "*"
    state: latest

- name: install commons
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - wget
    - htop
    - python3-minimal
    - net-tools
    - build-essential
    - ca-certificates
    - vim
    - nfs-common
    - rsyslog
    - libvirt-clients
    - sudo
    - apt-transport-https
    - gpg
    - locales-all
    - qemu-guest-agent
    - socat
