- name: allow access to ports
  firewalld:
    port: "{{item}}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 3000
    - 9090
    - 9093

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
