- name: add grafana repository
  yum_repository:
    name: grafana
    description: grafana repository
    baseurl: https://rpm.grafana.com
    gpgcheck: yes
    gpgkey: https://rpm.grafana.com/gpg.key

- name: install grafana
  yum:
    name: grafana
    state: present

- name: grafana dashboards
  vars:
    dashboards:
      - infraestrutura
  block:
    - name: grafana dashboards dir
      file:
        path: /etc/grafana/provisioning/dashboards/{{item}}
        state: directory
        mode: 0770
        owner: grafana
        group: grafana
      with_items: "{{dashboards}}"
    - name: grafana dashboards templates
      template:
        src: templates/dashboards.yml.j2
        dest: /etc/grafana/provisioning/dashboards/{{item}}.yaml
        mode: 0770
        owner: grafana
        group: grafana
      with_items: "{{dashboards}}"

- name: start and enable grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
