- name: add grafana repository
  yum_repository:
    name: grafana
    description: grafana repository
    baseurl: https://rpm.grafana.com
    gpgcheck: yes
    gpgkey: https://rpm.grafana.com/gpg.key

- name: install grafana
  yum:
    name: grafana
    state: present

- name: start and enable grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes
