- name: create prometheus system group and user
  block:
    - name: create group prometheus
      group:
        name: prometheus
        system: yes
    - name: create group prometheus
      user:
        name: prometheus
        system: yes
        group: prometheus

- name: create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: "{{become_user}}"
  with_items:
    - /var/lib/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/rules.d
    - /etc/prometheus/files_sd
    - /var/run/prometheus

- name: download and extract prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{prometheus_arch}}.tar.gz
    dest: /opt
    owner: prometheus
    group: "{{become_user}}"
    remote_src: yes

- name: install prometheus binaries
  file:
    state: link
    force: true
    src: "/opt/prometheus-{{ prometheus_version }}.linux-{{prometheus_arch}}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: "{{become_user}}"
    mode: a+x
  with_items:
    - prometheus
    - promtool

- name: create prometheus.yml
  vars:
    control_planes: "{{ hostvars[groups['controlplane']] }}"
    nodes: "{{ hostvars[groups['nodes']] }}"
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: 0770
    owner: prometheus
    group: "{{become_user}}"

- name: create prometheus.service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0770
    owner: prometheus
    group: "{{become_user}}"

- name: alermanager rules
  template:
    src: templates/rules.d/{{item}}.rules.j2
    dest: /etc/prometheus/rules.d/{{item}}.rules
    mode: 0770
    owner: prometheus
    group: alertmanager
  with_items:
    - infraestrutura

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: true
